full_name = input("Enter full name: ")
age = int(input("Enter age: "))
student_id = input("Enter student ID: ")
city = input("Enter city: ")
university = input("Enter university: ")
department = input("Enter department: ")
email = input("Enter email: ")
phone_number = int(input("Enter phone number: "))
favorite_programming_language = input("Enter favorite programming language: ")
programming_goal = input("Enter programming goal: ")

print("================================================")
print("             AKIBA STUDENT PROFILE              ")
print("================================================")
print()
print(f"Name:            {full_name}")
print(f"Student ID:      {student_id}")
print(f"Age:             {age}")
print(f"City:            {city}")
print(f"University:      {university}")
print(f"Department:      {department}")
print(f"Email:           {email}")
print(f"Phone:          0{phone_number}")
print(f"Favorite Language: {favorite_programming_language}")
print(f"Programming Goal:      \n{programming_goal}")
print()
print("================================================")