full_name = input("What is your full name?")
age = int(input("How old are you?"))
city = input("Which city do you live in?")
university = input("Which university do you study in?")
department = input("Which department are you studying in?")
favorite_language = input("What is your favorite programming language?")
programming_goal = input("What is your one programming goal?")

print("========================================")
print("      STUDENT INTRODUCTION     ")
print("========================================")
print("")
print(f"My name is {full_name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study {department} at {university}.")
print(f"My favorite programming language is {favorite_language}.")
print(f"My programming goal: \n {programming_goal}")
print("")
print("========================================")
