customer_name = input("Enter your name: ")
product_name = input("Enter the product name: ")
price = float(input("Enter price of the product: "))
quantity = int(input("Enter item quantity: "))

print("========================================")
print("              RECEIPT                   ")
print("========================================")
print()
print(f"Customer: {customer_name}")
print()
print(f"Product        Price       Qty")
print("----------------------------------------")
print(f"{product_name}        {price} ETB      {quantity}")
print()
print(f"Total:         {price*quantity} ETB")
print()
print("Thank you for shopping!")
print("========================================")