user_name = input("Enter name: ")
weight = float(input("Enter weight in kilograms: "))
height = float(input("Enter height in meters: "))

bmi = weight / (height * height)

print("================================")
print("           BMI REPORT           ")
print("================================")
print()
print(f"Name: {user_name}")
print(f"Weight: {weight} kg")
print(f"Height: {height:.2f} m")
print()
print(f"BMI: {bmi:.2f}")
print("================================")
